kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.app }}
  labels:
    app: {{ .Values.app }}
spec:
  accessModes: {{- .Values.persistentVolumeClaim.accessModes | toYaml | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.resources.requests.storage }}
  volumeMode: {{ .Values.persistentVolumeClaim.volumeMode }}