kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.app }}-api
  labels:
    app: {{ .Values.app }}
spec:
  to:
    kind: Service
    name: {{ .Values.app }}
  port:
    targetPort: minio-api
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
