kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.app }}
  labels:
    app: {{ .Values.app }}
spec:
  selector:
    app: {{ .Values.app }}
  ports:
    - name: minio-api
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: minio-ui
      protocol: TCP
      port: 9090
      targetPort: 9090
